apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: copy
spec:
  version: {{ .TagName }}
  homepage: https://github.com/a13x22/kube-copy
  shortDescription: Copy Kubernetes resources across namespaces and clusters
  description: |
    Intelligently copies Kubernetes resources with automatic metadata sanitization
    and conflict detection. Supports recursive dependency graph traversal to copy
    a resource along with its ConfigMaps, Secrets, Services, Ingresses, and more.

    Features:
    - Cross-namespace and cross-cluster copying
    - Smart sanitization (strips clusterIP, nodePort, PV bindings, etc.)
    - Conflict detection (existence, address, missing references)
    - Recursive mode to copy entire dependency graphs
    - Dry-run mode with table/yaml/json output
  caveats: |
    This plugin requires read access to the source namespace/cluster and
    create access to the target namespace/cluster.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/a13x22/kube-copy/releases/download/{{ .TagName }}/kubectl-copy-linux-amd64.tar.gz" .TagName }}
    bin: kubectl-copy
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/a13x22/kube-copy/releases/download/{{ .TagName }}/kubectl-copy-linux-arm64.tar.gz" .TagName }}
    bin: kubectl-copy
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/a13x22/kube-copy/releases/download/{{ .TagName }}/kubectl-copy-darwin-amd64.tar.gz" .TagName }}
    bin: kubectl-copy
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/a13x22/kube-copy/releases/download/{{ .TagName }}/kubectl-copy-darwin-arm64.tar.gz" .TagName }}
    bin: kubectl-copy
