package sanitizer

import (
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

func init() {
	Register("Job", SanitizerFunc(sanitizeJob))
	Register("CronJob", SanitizerFunc(sanitizeCronJob))
}

func sanitizeJob(obj *unstructured.Unstructured) []Warning {
	var warnings []Warning
	identifier := fmt.Sprintf("Job/%s", obj.GetName())

	// Strip controller-generated labels
	labels := obj.GetLabels()
	if labels != nil {
		controllerLabels := []string{
			"batch.kubernetes.io/job-name",
			"controller-uid",
			"batch.kubernetes.io/controller-uid",
			"job-name",
		}
		changed := false
		for _, l := range controllerLabels {
			if _, ok := labels[l]; ok {
				delete(labels, l)
				changed = true
			}
		}
		if changed {
			if len(labels) == 0 {
				obj.SetLabels(nil)
			} else {
				obj.SetLabels(labels)
			}
			warnings = append(warnings, Warning{
				Resource: identifier,
				Message:  "removed controller-generated labels",
			})
		}
	}

	// Strip the same labels from the pod template
	stripJobLabelsFromTemplate(obj, identifier, &warnings)

	// Remove selector (auto-generated by controller, contains controller-uid)
	spec, ok := obj.Object["spec"].(map[string]interface{})
	if !ok {
		return warnings
	}
	if _, ok := spec["selector"]; ok {
		delete(spec, "selector")
		warnings = append(warnings, Warning{
			Resource: identifier,
			Message:  "removed auto-generated selector to let the controller create a new one",
		})
	}

	return warnings
}

func sanitizeCronJob(obj *unstructured.Unstructured) []Warning {
	// CronJobs themselves do not need much specific sanitization beyond common.
	// The Job template inside them will be handled by the Job controller at runtime.
	return nil
}

func stripJobLabelsFromTemplate(obj *unstructured.Unstructured, identifier string, warnings *[]Warning) {
	spec, ok := obj.Object["spec"].(map[string]interface{})
	if !ok {
		return
	}
	template, ok := spec["template"].(map[string]interface{})
	if !ok {
		return
	}
	tmplMeta, ok := template["metadata"].(map[string]interface{})
	if !ok {
		return
	}
	labels, ok := tmplMeta["labels"].(map[string]interface{})
	if !ok {
		return
	}

	controllerLabels := []string{
		"batch.kubernetes.io/job-name",
		"controller-uid",
		"batch.kubernetes.io/controller-uid",
		"job-name",
	}
	changed := false
	for _, l := range controllerLabels {
		if _, ok := labels[l]; ok {
			delete(labels, l)
			changed = true
		}
	}
	if changed {
		*warnings = append(*warnings, Warning{
			Resource: identifier,
			Message:  "removed controller-generated labels from pod template",
		})
	}
}
